Опциональная установка SendCityCode и RecCityCode
appwilio/cdek-sdk pull request #4
Opened 2018-07-22 16:10 UTC by Volga

Добавлена возможность указать SendCityCode и RecCityCode равными null, посредством установки cвойства Code модели City равного 0. Т.к. API СДЭК устанавливает данные параметры как необязательные, а справочник городов СДЭК представлен не в очень удобной форме - таблицах Excel - в реальной жизни в большинстве случаев удобно указать только почтовый индекс городов отправления и получения.

2018-07-23 21:27 UTC, greabock requested changes

2018-07-23 21:27 UTC, greabock commented on src/Common/Order.php
> +        return $this->SendCity ? $this->SendCity->getCode() ?: null : null;
Расставьте, пожалуйста, скобки в тернарниках.
Дело в том, что приоритет операций тернарных операторов в php отличается, от того как работают тернарники в других языках (js, python, etc). Во избежание путаницы, при использовании составных тернарных операторов в php следует использовать скобки, для явной расстановки приоритетов операций.

2018-07-23 21:27 UTC, greabock commented on src/Common/Order.php
> +        return $this->RecCity ? $this->RecCity->getCode() ?: null : null;
тоже самое

2018-07-23 21:37 UTC, greabock commented on src/Common/Order.php
> +        return $this->SendCity ? $this->SendCity->getCode() ?: null : null;
возможно лучше вообще разложить это на 
```php
if ($this->SendCity) {
    return $this->SendCity->getCode() ?: null;
}
return null;
```

2018-07-23 21:38 UTC, greabock commented on src/Common/Order.php
> +        return $this->SendCity ? $this->SendCity->getCode() ?: null : null;
впрочем, просто расставьте скобки, спасибо

2018-07-23 21:44 UTC, jhaoda commented
@Volga не очень понимаю...
Т.е. вы передали в заказ город в виде `City::create(['PostCode' => '1276', 'Code' => 0])`, потом заказ сериализуется и `0` превращается в `null`?

А если `Code` не передавать, то во что он сериализуется?

2018-07-24 07:54 UTC, Volga commented
@jhaoda, Если ничего не передать - будет Exception "Return value of Appwilio\CdekSDK\Common\City::getCode() must be of the type integer, null returned", как и есть сейчас.

2018-07-24 14:06 UTC, jhaoda commented
@Volga а если ослабить типизацию до `getCode(): ?int`, то поможет?

2018-07-24 18:03 UTC, Volga commented
@jhaoda, согласен - поможет.
Закрываю этот запрос. Ослабление типизации оформил отдельным запросом: [https://github.com/appwilio/cdek-sdk/pull/5](url)

2018-07-24 18:03 UTC, closed without merging